# Generated by Django 5.2.4 on 2025-08-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycleable',
            name='quantity',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='recycleable',
            name='recycled',
            field=models.BooleanField(default=True),
        ),
    ]
