# Generated by Django 5.2.5 on 2025-08-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recycleable_quantity_recycleable_recycled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='not_working_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='working_price',
        ),
        migrations.AddField(
            model_name='item',
            name='prediction_price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recycleable',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
